global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'real-time-auction'
    static_configs:
      - targets: ['host.docker.internal:5000']
        labels:
          app: 'auction-api'
          environment: 'development'

    metrics_path: '/metrics'
    scrape_interval: 10s
